version: '3.8'

services:
  server:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./:/code/
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    expose:
      - 5432
    env_file:
      - .env

volumes:
  postgres_data:
